# Start App

services:
  node:
    container_name: guia-linux
    build:
      context: ../../../docker/node
    image: guia-linux:node-nvm-22
    environment:
      - NODE_VERSION=22
    volumes:
      - C:/host/var-www/html/guia-linux:/app
    working_dir: /app
    stdin_open: true
    tty: true
    ports:
      - "5173:5173"